### PR TITLE
Create TEMPLATE.txt

### PR DESCRIPTION
**Pull request by vpnarea**
TEMPLATE configuration for VPNArea.com

### CODE REVIEW

**Comment by Zomboided** [comment]
I haven't spent a bunch of time looking at this, but currently the template is making the user key and cert optional by using the remove tag, which isn't supported (a provider is marked as either not needing a key and cert, needing a single key and cert, or needing multiple keys and certs.

**Comment by vpnarea** [comment]
I was under the impression that with the current configuration some Servers will be using only CA certificate and others will be using CA,Client Cert and Key and TLS Auth key. 
Some of our servers require only CA Cert while others require CA Cert, Client Cert, Client Key and TLS Auth key.
Wouldn't the REMOVE Tag specified in LOCATIONS remove only selectively the mentioned certificates/keys in accordance with the servers who need them and vice versa? We've specified #REMOVE=1 and #REMOVE=2 accordingly so that specific set of keys/certs is used for some servers and not used for others?

If not how would you advice we configure the settings so that different CA certificate can be used for different servers and so that some servers can use additional certs/keys while others don't?

Can we just upload .ovpn files with embed necessary keys in them? Without TEMPLATE.TXT and LOCATIONS.TXT?

**Comment by vpnarea** [comment]
We need multiple keys and certs (including different ca cert) for some locations and single different CA Cert for other locations.

**Comment by vpnarea** [comment]
We could structure the files like this, in .ovpn format, will that work? https://github.com/Zomboided/service.vpn.manager/tree/master/LimeVPN

**Comment by Zomboided** [comment]
The client/user key and cert is the issue.  Each provider either has a user key/cert component, or it doesn't.  If a provider is marked as needing a cert, then the addon will ask for one - this isn't location independent.  It doesn't get this information from the ovpn, so uploading the ovpns is not gonna work as it does for Lime.  For the other certs, etc there's no issue in either using the ovpn or using the REMOVE tagging approach.

Ironically here, the best approach is probably to use the User Defined and have your users gather together all of the files and run them through the wizard.  Providing all of the files exist when they do the import everything should be good.

**Comment by vpnarea** [comment]
We've removed the servers requiring different certificates from the equation. Currently all servers in LOCATIONS.txt will require only the "ca.crt" certificate.

**Pull request merged**
