### PR TITLE
Fix NordVPN authentication

### PR DESCRIPTION
**Pull request by gibbsnich**
Hi,

does NordVPN authentication really work for you? 
I really made sure my password was correct but it just would not connect. 
Made this little change [0] and it works, hence my question. 
Just proposing this because it did not work otherwise..

Best regards

### CODE REVIEW

**Comment by Zomboided** [comment]
Yes, otherwise i'd have not claimed it worked...
However, I can believe this fixes a problem where non-letter/English characters are used...this is a known problem.  Did your password have such characters in it?

**Comment by gibbsnich** [comment]
Of course I thought so, because the addon is excellent, so I thought this was odd. (Didn't intend to sound disrespectful..)
But this could explain it: yes I'm using some special chars.

**Comment by Zomboided** [comment]
Can you change your password to plain english text please and test, then
I'll pick this change up if we're all good.
I can't test this any more because my Nord ID is expired.
Thanks for this patch.

**Comment by gibbsnich** [comment]
Yes it's still working. 
Thanks for this tool! I'm really glad I could help make it even (a little) netter!
( Didn't know this is a known issue.. I don't read FAQs I RTFS 😅)

**Pull request merged**
