### PR TITLE
replace platform.py by svm_platform.py to avoid interference with Python

### PR DESCRIPTION
**Pull request by awiouy**
On LibreELEC, `platform.py` provided by VPN Manager for OpenVPN overrides `platform.py` provided by Python, which breaks other addons which import `platform`, for example youtube-dl Control.

This pull request therefore renames `platform.py` to `svm_platform.py` to avoid conflicts.

With this fix, VPN Manager for OpenVPN and youtube-dl Control both work as expected.

### CODE REVIEW

**Comment by peno64** [comment]
This is something I reported to the developer a year ago or so and he never wanted to fix this...
Glad that I am not the only one having this problem.

**Comment by Zomboided** [comment]
@Anton, when peno64 whined excessively to me about this, I went and read a
bunch of python documentation and concluded that what I was doing was
legitimate (can't find the links now, don't have time at the mo).  My
interpretation was that it would import something in the local package,
otherwise it would import something from the sys.path.  So if another addon
was trying to import 'package', it would not find something squirrelled
away in my addon before finding the 'standard' version.

So I can see that your change would work, no problem with that, but are we
sure here that LE is doing the right thing with regards to paths
generally?  Is there something unique about the way LE uses Python that
means it doesn't behave as I've interpreted the documentation.  Or am I
just not interpreting the documentation correctly?

**Comment by peno64** [comment]
see https://github.com/Zomboided/service.vpn.manager/issues/205

**Comment by awiouy** [comment]
This issue involves several packages: Python on LibreELEC, Kodi, VPN Manager for OpenVPN, youtube-dl Control, etc.

I could not find why youtube-dl Control picks up `platform.py` from VPN Manager for OpenVPN rather than from Python.

A modified version of Librespot correctly refers to `platform.py` from Python.

The problem may therefore be caused by how LibreELEC or Kodi load python libraries of addons, probably in alphabetical order.

Anyways, renaming `platform.py` in this addon is purely esthetic and fixes the problem, whatever causes it.

**Comment by peno64** [comment]
I just made a fresh install of osmc with kodi. osmc is another linux OS that can be used on raspberry to run kodi. I only installed vpn manager and an addon to test the conflict and exactly the same issue is there. widevine cdm cannot be installed. When I replace platform.py with a renamed version, then everything installs and runs fine.
This proofs that the problem is not libreelec specific.

**Pull request merged**
